using UnityEngine;

public class EnemyAxe : MonoBehaviour
{

    [SerializeField] private GameObject impactFx; 
    [SerializeField] private Rigidbody rb;
    [SerializeField] private Transform axeVisial;


    private Vector3 direction;
    private Transform player;
    private float flySpeed;
    private float rotationSpeed;
    private float timer = 1;

    public void AxeSetup(float flySpeed, Transform player, float timer)
    {
        rotationSpeed = 1600; 
        
        this.flySpeed = flySpeed;
        this.player = player;   
        this.timer = timer;
    }


    private void Update()
    {
        axeVisial.Rotate(Vector3.right * rotationSpeed * Time.deltaTime);
        timer -= Time.deltaTime;

        if (timer > 0)
            direction = player.position + Vector3.up - transform.position;

        rb.linearVelocity = direction.normalized * flySpeed;

        transform.forward = rb.linearVelocity;
    }


    private void OnTriggerEnter(Collider other)
    {
        Bullet bullet = other.GetComponent<Bullet>();
        Player player = other.GetComponent<Player>();

        if (bullet != null || player != null)
        {
            GameObject newFx = ObjectPool.instance.GetObject(impactFx); 
            newFx.transform.position = transform.position;  
            
            ObjectPool.instance.ReturnObject(gameObject);
            ObjectPool.instance.ReturnObject(newFx, 1f); 
        }
    }
}








